language: objective-c
osx_image: xcode6.4
xcode_project: RGLockbox.xcodeproj
xcode_scheme: RGLockbox-Tests
xcode_sdk: iphonesimulator8.4
script:
- xctool -project RGLockbox.xcodeproj -scheme RGLockbox-Tests build test -sdk iphonesimulator8.4 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
