language: objective-c
osx_image: xcode7.2
xcode_project: RGLockbox.xcodeproj
xcode_scheme: RGLockbox-Tests
xcode_sdk: iphonesimulator9.1
script:
- xctool -project RGLockbox.xcodeproj -scheme RGLockbox-Tests build test -sdk iphonesimulator9.1 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
